baseurl: 'https://awesome.ipfs.tech'
relativeurls: true
languageCode: en
pluralizelisttitles: false
removePathAccents: true
canonifyURLs: true
title: Awesome IPFS

disableKinds:
  - taxonomyTerm

params:
  Description: >-
    Useful resources for using IPFS and building things on top of it
  image: /images/banner.png
